services:
  ara-dev-front-migration:
    image: ara-dev-front-migration
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 15022:3000